### ISSUE TITLE
Source package does not contain license

### ISSUE THREAD

**Issue by vlna** [jouni/restrain#2]
nor information about license.

Information about license is available only from page https://vaadin.com/directory#!addon/restrain

**Comment by jouni** [comment]
Added a license file to the repo and license mention in the readme.

I don’t have the time right now to update the source package. How important is that?

**Comment by vlna** [comment]
Nice. Thx.

For me repo update is clear enough.

Issue fixed in  @3448e41d63210f62c5e78e3baeeb109c2c44f5c5 and in @2bfaa8f2526dc53196e690a67e537899167e9060
